ci: adapt to downstream changes

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -39,33 +39,39 @@ jobs:
       - name: Build
         run: |
           .downstream/build.py . -tl \
-            --report "$RUNNER_TEMP/report.md" \
-            --mappings "$RUNNER_TEMP/mappings" \
-            --gh-repo "${{ github.repository }}" \
-            --gh-run-id "${{ github.run_id }}" \
-            --gh-run-attempt "${{ github.run_attempt }}"
+            --report "$RUNNER_TEMP/report.json" \
+            --mappings "$RUNNER_TEMP/mappings"
+
+      - name: Render build report
+        uses: ./.downstream/actions/build-report
+        with:
+          report-path: ${{ runner.temp }}/report.json
+          output-path: ${{ runner.temp }}/report.md
 
       - name: Add report to job summary
-        if: ${{ !cancelled() }} # Even if build fails
         run: cat "$RUNNER_TEMP/report.md" >> "$GITHUB_STEP_SUMMARY"
 
       - name: Upload build report
-        if: ${{ !cancelled() }} # Even if build fails
         uses: actions/upload-artifact@v7
         with:
           name: build-report
-          path: ${{ runner.temp }}/report.md
+          path: ${{ runner.temp }}/report.json
 
       - name: Upload build mappings
-        if: ${{ !cancelled() }} # Even if build fails
         uses: actions/upload-artifact@v7
         with:
           name: build-mappings
           path: ${{ runner.temp }}/mappings/
 
       - name: Upload build cache
-        if: ${{ !cancelled() }} # Even if build fails
         uses: actions/upload-artifact@v7
         with:
           name: build-cache
           path: ${{ runner.temp }}/cache/
+
+      - name: Fail if critical repos are not green
+        run: |
+          if ! jq .green "$RUNNER_TEMP/report.json" -e > /dev/null; then
+            echo "::error::At least one critical repo failed."
+            exit 1
+          fi
